apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notifications-ms
  name: notifications-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notifications-ms
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/tienda-ms-452101/image-registry/notifications-ms
        name: notifications-ms
        env:
        - name: PORT
          value: "3002"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notifications-secret
              key: database_url
        resources: {}
status: {}
